
    create table correctores (
        maximas_correcciones integer,
        id bigint generated by default as identity,
        identificador_usuario bigint,
        telefono varchar(255),
        primary key (id)
    );

    create table materias (
        id bigint generated by default as identity,
        nombre varchar(255) not null,
        primary key (id)
    );

    create table materias_en_convocatoria (
        id bigint generated by default as identity,
        id_convocatoria bigint,
        id_corrector bigint,
        id_materia bigint,
        primary key (id)
    );

    alter table if exists materias_en_convocatoria 
       add constraint FK3a3wsqwm15sh48o5botrqq0hk 
       foreign key (id_corrector) 
       references correctores;
