
    create table correctores (
        maximas_correcciones integer not null,
        id bigint generated by default as identity,
        identificador_usuario bigint not null unique,
        telefono varchar(255),
        primary key (id)
    );

    create table materias_en_convocatoria (
        id bigint generated by default as identity,
        id_convocatoria bigint not null,
        id_corrector bigint,
        id_materia bigint not null,
        primary key (id),
        unique (id_corrector, id_materia, id_convocatoria)
    );

    alter table if exists materias_en_convocatoria 
       add constraint FK3a3wsqwm15sh48o5botrqq0hk 
       foreign key (id_corrector) 
       references correctores;
