spring.application.name=corrector
# Configuracion de la base de datos H2 en memoria
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.datasource.url=jdbc:h2:./murphy
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa
spring.jpa.hibernate.ddl-auto=update
# Mostrar las consultas SQL en la consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Do NOT let Hibernate execute the DDL against a DB
spring.jpa.hibernate.ddl-auto=none
# Tell Hibernate to generate the DDL script on startup
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=ddl-script.sql
# Optional – show the SQL that would be executed (helps debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true